resolver: lts-9.4

packages:
- '.'
extra-deps:
- time-interval-0.1.1
- time-units-1.0.0
- time-out-0.2
- attoparsec-conduit-1.1.0
- blaze-builder-conduit-1.1.0
- crypto-numbers-0.2.3
- crypto-pubkey-0.2.4
- data-default-instances-base-0.0.1
- network-conduit-1.1.0
- publicsuffixlist-0.1
- shakespeare-css-1.1.0
- shakespeare-i18n-1.1.0
- shakespeare-js-1.3.0
- shakespeare-text-1.1.0
- wai-test-3.0.0
- yesod-routes-1.2.0.7
- heroku-0.1.2.3
# - heroku-persistent-0.2.0
# - persistent-database-url-1.1.0

flags: {}

extra-package-dbs: []
